### ISSUE TITLE
fix spelling on exercise readme.md

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/contributor-playground#149] opened 2018-12-10 21:10 UTC
https://github.com/kubernetes-sigs/contributor-playground/tree/master/exercises

**Comment by rajathagasthya** [comment] 2018-12-10 21:16
Dupe of #138 ;)

**Comment by guineveresaenger** [comment] 2019-01-04 00:40
Closing this for cleanup - remember you can always `/reopen` if you like!

/close

**Closed by guineveresaenger** 2019-01-04 00:40 UTC
Labels: kind/bug, priority/important-soon, sig/contributor-experience, ¯\_(ツ)_/¯
